<a href="https://colab.research.google.com/github/Moussaoui-Ghiles/Pytorch/blob/main/nn_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F 
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import numpy as np



In [5]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [6]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [7]:
# Define model
model = nn.Linear(3, 2)

print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4043,  0.1446,  0.0162],
        [ 0.1300, -0.3478,  0.4089]], requires_grad=True)
Parameter containing:
tensor([0.3771, 0.2327], requires_grad=True)


In [8]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4043,  0.1446,  0.0162],
         [ 0.1300, -0.3478,  0.4089]], requires_grad=True),
 Parameter containing:
 tensor([0.3771, 0.2327], requires_grad=True)]

In [9]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 40.2783,   3.9988],
        [ 50.9332,   7.6205],
        [ 55.8704, -11.3516],
        [ 48.4362,  13.6623],
        [ 43.2920,   4.4318],
        [ 40.5381,   4.4766],
        [ 50.8048,   8.3772],
        [ 56.2909, -10.8128],
        [ 48.1765,  13.1845],
        [ 42.9039,   4.7107],
        [ 40.1499,   4.7555],
        [ 51.1929,   8.0983],
        [ 55.9988, -12.1083],
        [ 48.8243,  13.3834],
        [ 43.0323,   3.9540]], grad_fn=<AddmmBackward0>)

In [10]:
# Define loss function
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(5684.6631, grad_fn=<MseLossBackward0>)


In [11]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [12]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [13]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 466.8171
Epoch [20/100], Loss: 385.9630
Epoch [30/100], Loss: 450.8163
Epoch [40/100], Loss: 284.3623
Epoch [50/100], Loss: 221.5199
Epoch [60/100], Loss: 98.9681
Epoch [70/100], Loss: 65.1171
Epoch [80/100], Loss: 58.6241
Epoch [90/100], Loss: 33.0207
Epoch [100/100], Loss: 18.4884


In [16]:
# Generate predictions
preds = model(inputs)
preds


tensor([[ 58.4185,  71.6609],
        [ 80.0150, 100.8042],
        [119.3915, 129.6806],
        [ 29.5004,  45.2033],
        [ 93.4326, 114.6966],
        [ 57.3360,  70.7900],
        [ 79.4560, 100.8848],
        [119.5107, 130.3279],
        [ 30.5829,  46.0742],
        [ 93.9561, 115.6481],
        [ 57.8594,  71.7415],
        [ 78.9325,  99.9333],
        [119.9505, 129.6001],
        [ 28.9769,  44.2518],
        [ 94.5151, 115.5675]], grad_fn=<AddmmBackward0>)

In [17]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])